In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("C:\\Users\\panka\\OneDrive\\Desktop\\marketing ab\\Marketing-AB-Testing\\marketing_AB.csv")
df

,Unnamed: 0,user id,test group,converted,total ads,most ads day,most ads hour
0,0,1069124,ad,False,130,Monday,20
1,1,1119715,ad,False,93,Tuesday,22
2,2,1144181,ad,False,21,Tuesday,18
3,3,1435133,ad,False,355,Tuesday,10
4,4,1015700,ad,False,276,Friday,14
...,...,...,...,...,...,...,...
588096,588096,1278437,ad,False,1,Tuesday,23
588097,588097,1327975,ad,False,1,Tuesday,23
588098,588098,1038442,ad,False,3,Tuesday,23
588099,588099,1496395,ad,False,1,Tuesday,23
588100,588100,1237779,ad,False,1,Tuesday,23

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588101 entries, 0 to 588100
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Unnamed: 0     588101 non-null  int64
 1   user id        588101 non-null  int64
 2   test group     588101 non-null  object
 3   converted      588101 non-null  bool
 4   total ads      588101 non-null  int64
 5   most ads day   588101 non-null  object
 6   most ads hour  588101 non-null  int64
dtypes: bool(1), int64(4), object(2)
memory usage: 27.5+ MB

In [5]:
duplicates = df[df.duplicated('user id', keep=False)]
duplicates

Empty DataFrame
Columns: [Unnamed: 0, user id, test group, converted, total ads, most ads day, most ads hour]
Index: []

In [6]:
# Calculate Q1 (25th percentile) and Q3 (75th percentile)
numeric_cols = df.select_dtypes(include=['number'])
Q1 = numeric_cols.quantile(0.25)
Q3 = numeric_cols.quantile(0.75)

# Calculate the Interquartile Range (IQR)
IQR = Q3 - Q1

# Define outliers as points outside 1.5 * IQR range
outliers = ((numeric_cols < (Q1 - 1.5 * IQR)) | (numeric_cols > (Q3 + 1.5 * IQR)))

# Print outliers for each column
outliers_count = outliers.sum()
print("Number of outliers in each column:")
print(outliers_count)

# Optionally, filter the outliers from the DataFrame
df_outliers = numeric_cols[outliers.any(axis=1)]
print("Data points considered as outliers:")
print(df_outliers)

Number of outliers in each column:
Unnamed: 0           0
user id              0
total ads        52057
most ads hour     5536
dtype: int64
Data points considered as outliers:
        Unnamed: 0  user id  total ads  most ads hour
0                0  1069124        130             20
1                1  1119715         93             22
3                3  1435133        355             10
4                4  1015700        276             14
5                5  1137664        734             10
...            ...      ...        ...            ...
584639      584639  1004190          1              0
584640      584640  1028589          1              0
584641      584641  1536866          1              0
584642      584642  1089798          1              0
584643      584643  1096523          1              0

[57135 rows x 4 columns]

In [7]:
df.isna().sum()

Unnamed: 0       0
user id          0
test group       0
converted        0
total ads        0
most ads day     0
most ads hour    0
dtype: int64

In [8]:
cont_var = ['total ads','most ads hour']
cat_var = ['test group','converted','most ads day']